Feature/warehouse entity
alansiq/projeto_integrador pull request #10
Opened 2022-04-26 17:09 UTC by hugofellipecruz

Created warehohuse entity.

This PR contains:
- Entity
- Controller
- Repository
- Service
- 2 Exceptions
- Tests

2022-04-26 18:14 UTC, alansiq requested changes
Faltam poucas correções para o merge. Fora isso, tudo ok.

2022-04-26 18:14 UTC, alansiq commented on src/test/java/com/mercadolivre/bootcamp/projeto_integrador/unit/WarehouseServiceTest.java
> +    void shouldFindAllWarehouses(){
Algumas alterações nos testes:

- O `warehouseRepository` e `warehouseService` foram criados e mockados em nível de classe e também em cada um dos métodos em duplicidade... Pode deixar apenas em nível de classe com as annotations @Mock e @InjectMocks
- O teste "shouldFindAllWarehouses()" não precisa salvar uma nova warehouse. Você pode remover as linhas abaixo completamente: 
```java
        Warehouse warehouse = Warehouse.builder().warehouseId(warehouseId).build();
        WarehouseServiceImpl warehouseService = new WarehouseServiceImpl(wareHouseRepository);
        warehouseService.save(warehouse);
        warehouseList.add(warehouse);
```
- Ao invés de `assertNotNull` você pode utilizar:
```java
assertEquals(warehouseList, whList);
```

2022-04-26 18:14 UTC, alansiq commented on src/test/java/com/mercadolivre/bootcamp/projeto_integrador/unit/WarehouseServiceTest.java
> +    void shouldFindWarehouseById(){
Novamente `warehouseRepository` e `warehouseService` criado em duplicidade. Podemos remover eles aqui também, por favor?

2022-04-26 18:14 UTC, alansiq commented on src/test/java/com/mercadolivre/bootcamp/projeto_integrador/unit/WarehouseServiceTest.java
> +        warehouseService.save(warehouse);
Não é necessário utilizar o .save() em um teste de findwarehouseById - podemos seguir com as warehouses criadas no // Arrange em nível de classe ou com a warehouse criada dentro do próprio teste.

2022-04-26 18:14 UTC, alansiq commented on src/test/java/com/mercadolivre/bootcamp/projeto_integrador/unit/WarehouseServiceTest.java
> +        assert test;
Para seguir o padrão utilizado em outros testes, poderia utilizar o `assertTrue(test);` por gentileza?

2022-04-26 18:14 UTC, alansiq commented on src/test/java/com/mercadolivre/bootcamp/projeto_integrador/unit/WarehouseServiceTest.java
> +public class WarehouseServiceTest {
Criar teste para método save de WarehouseService

2022-04-26 19:53 UTC, hugofellipecruz commented on src/test/java/com/mercadolivre/bootcamp/projeto_integrador/unit/WarehouseServiceTest.java
> +    void shouldFindAllWarehouses(){
Precisei utilizar o warehouseList.add(warehouse); para não cair no caso onde a lista está vazia, de resto tudo foi corrigido

2022-04-27 12:41 UTC, alansiq approved these changes
LGTM

2022-04-27 12:41 UTC, merged