feature/inboundorder_controller
alansiq/projeto_integrador pull request #36
Opened 2022-04-28 19:12 UTC by alansiq

2022-04-29 13:26 UTC, victosantos commented on src/main/java/com/mercadolivre/bootcamp/projeto_integrador/dto/NewBatchStockDTO.java
> +                .price(this.price)
Linhas 42 e 43: pq esta pegando do this?

2022-04-29 13:26 UTC, victosantos commented on src/main/java/com/mercadolivre/bootcamp/projeto_integrador/dto/NewBatchStockDTO.java
> +
Curiosidade: Pra q serve esse maps?

2022-04-29 13:27 UTC, victosantos commented on src/main/java/com/mercadolivre/bootcamp/projeto_integrador/entity/Section.java
> +//    private List<InBoundOrder> listInBoundOrder;
Pode apagar em vez de comentar

2022-04-29 14:09 UTC, victosantos commented on src/main/java/com/mercadolivre/bootcamp/projeto_integrador/factory/InBoundOrderFactory.java
> +        if(!isWarehouseValid) throw new IdNotFoundException(warehouseId);
isValidWarehouse já lança a exception

2022-04-29 14:12 UTC, victosantos commented on src/main/java/com/mercadolivre/bootcamp/projeto_integrador/factory/InBoundOrderFactory.java
>                  .isRepresentativeAssociatedWithSection(representativeId, sectionId);
apagar linha 55 do representativeservice (esta apenas inicializando variavel)

2022-04-29 14:14 UTC, victosantos commented on src/main/java/com/mercadolivre/bootcamp/projeto_integrador/factory/InBoundOrderFactory.java
> +        if (!sectionHasEnoughCapacity) throw new SectionDoesNotHaveEnoughCapacityException(sectionId, totalVolume);
mesma coisa exception na service em vez de fazer aqui

2022-04-29 14:54 UTC, victosantos commented on src/main/java/com/mercadolivre/bootcamp/projeto_integrador/dto/InboundOrderDTO.java
> +public class InboundOrderDTO {
alterar nome dto

2022-04-29 14:54 UTC, victosantos commented on src/main/java/com/mercadolivre/bootcamp/projeto_integrador/dto/NewBatchStockDTO.java
> +public class NewBatchStockDTO {
alterar nome dto

2022-04-29 15:00 UTC, victosantos commented on src/main/java/com/mercadolivre/bootcamp/projeto_integrador/service/SectionServiceImpl.java
> +        Optional<Section> sectionOptional = sectionRepository.findById(sectionID);
add exception aqui

2022-04-29 15:02 UTC, victosantos commented on src/main/resources/data.sql
> +INSERT INTO representative (full_name, section_id) VALUES ('RAFA', 6);
add linha vazia boa pratica

2022-04-29 15:10 UTC, victosantos requested changes
alguns pontos a serem considerados

2022-04-29 15:42 UTC, alansiq commented on src/main/java/com/mercadolivre/bootcamp/projeto_integrador/factory/InBoundOrderFactory.java
>          boolean sectionHasEnoughCapacity = sectionService.availableSectionCapacity(totalVolume, sectionId);
Utilizamos o .compareTo quando o tipo é BigDecimal

> Parameters:This function accepts only one BigDecimal object of BigDecimal type for comparison with this BigDecimal object.
Return Value:This method can return the following values :
0 : if value of this BigDecimal is equal to that of BigDecimal object passed as parameter.
1 : if value of this BigDecimal is greater than that of BigDecimal object passed as parameter.
-1 : if value of this BigDecimal is less than that of BigDecimal object passed as parameter.

--- 

Ou seja:

```java
getSection.getCapacity().compareTo(totalVolume) >= 0;
```

É igual a:

```java
getSection.getCapacity() >= totalVolume;
```

2022-04-29 17:09 UTC, alansiq commented on src/main/java/com/mercadolivre/bootcamp/projeto_integrador/factory/InBoundOrderFactory.java
> +    private void validateStockValid(BatchStock batchStock, Long sectionId) {
PS: Entendi lendo mais pra baixo que é pra migrar as exceptions né? fazendo

2022-04-30 15:43 UTC, alansiq commented
> alguns pontos a serem considerados

Correções realizadas

2022-05-02 21:23 UTC, victosantos approved these changes

2022-05-02 21:23 UTC, merged