Feature/updating representative service
alansiq/projeto_integrador pull request #41
Opened 2022-04-29 15:27 UTC by marianna-meli

resolving backlog: updating representative entity, service and serviceImpl and tests.

2022-04-29 19:50 UTC, rafaelluiz-meli commented on src/main/java/com/mercadolivre/bootcamp/projeto_integrador/controller/RepresentativeController.java
> +    public ResponseEntity<?> updateRepresentative(@PathVariable(value = "id") @Valid @RequestBody Representative representative) {
Este método deve retornar um Representative ou um RepresentativeDTO. Como não tem nenhum DTO criado para esta Entity alterar de ResponseEntity<?> para ResponseEntity<Representative>. 
Também não vamos ter o id como @PathVariaable, apenas @Valid @RequestBody Representative representative como parâmetros deste Endpoint. Neste caso remover o @PathVariable(value - "id") do updateRepresentative

2022-04-29 19:51 UTC, rafaelluiz-meli commented on src/main/java/com/mercadolivre/bootcamp/projeto_integrador/controller/RepresentativeController.java
>      @PutMapping("/representative/{id}")
Remover o "/{id}"da Annotation @PutMapping

2022-04-29 20:01 UTC, rafaelluiz-meli requested changes
Verifique as alterações que foram solicitadas.

2022-05-04 13:27 UTC, marianna-meli commented on src/main/java/com/mercadolivre/bootcamp/projeto_integrador/controller/RepresentativeController.java
> +    public ResponseEntity<?> updateRepresentative(@PathVariable(value = "id") @Valid @RequestBody Representative representative) {
Alterações realizadas.

2022-05-04 13:27 UTC, marianna-meli commented on src/main/java/com/mercadolivre/bootcamp/projeto_integrador/controller/RepresentativeController.java
>      @PutMapping("/representative/{id}")
Alterações realizadas.

2022-05-04 14:22 UTC, merged