enchatment/newPurchaseOrderDto-refactoring
alansiq/projeto_integrador pull request #42
Opened 2022-04-29 17:28 UTC by victosantos

2022-04-29 19:28 UTC, rafaelluiz-meli commented on src/main/java/com/mercadolivre/bootcamp/projeto_integrador/service/PurchaseOrderItemsService.java
> +    PurchaseOrderItems updatePurchaseOrderItens(PurchaseOrderItems purchaseOrderItems);
Alterar nome do método updatePurchaseOrderItens para updatePurchaseOrderItems

2022-04-29 19:29 UTC, rafaelluiz-meli commented on src/main/java/com/mercadolivre/bootcamp/projeto_integrador/service/PurchaseOrderItemsService.java
> +    void deletePurchaseOrderItens(Long purchaseOrderItensId);
Alterar nome do método de deletePurchaseOrderItens para deletePurchaseOrderItems

2022-04-29 19:30 UTC, rafaelluiz-meli commented on src/main/java/com/mercadolivre/bootcamp/projeto_integrador/service/PurchaseOrderItemsService.java
> +    PurchaseOrderItems findById(Long purchaseOrderItensId);
Alterar o nome do parâmetro do método de purchaseOrderItensId para purchaseOrderItemsId

2022-04-29 19:32 UTC, rafaelluiz-meli commented on src/main/java/com/mercadolivre/bootcamp/projeto_integrador/service/PurchaseOrderItemsService.java
> +    List<PurchaseOrderItems> getAllPurchaseOrderItens();
Alterar o nome do método de getAllPurchaseOrderItens para getAllPurchaseOrderItems

2022-04-29 19:33 UTC, rafaelluiz-meli commented on src/main/java/com/mercadolivre/bootcamp/projeto_integrador/service/PurchaseOrderItemsService.java
> +    PurchaseOrderItems addPurchaseOrderItens(NewPurchaseOrderItemsDTO purchaseOrderItensDTO);
Alterar o nome do método addPurchaseOrderItens para addPurchaseOrderItems e alterar o nome da variável do parâmetro de purchaseOrderItensDTO para purchaseOrderItemsDTO

2022-04-29 19:36 UTC, rafaelluiz-meli commented on src/main/java/com/mercadolivre/bootcamp/projeto_integrador/dto/purchase_order_items/NewPurchaseOrderItemsDTO.java
>  @Data
Usar @Data não é uma boa prática, utilize @Getter e @Setter no lugar e as anotações dos construtores: @AllArgsConstructor e @NoArgsContructor

2022-04-29 19:39 UTC, rafaelluiz-meli commented on src/test/java/com/mercadolivre/bootcamp/projeto_integrador/unit/PurchaseOrderItemsTest.java
Utilizar a anotação @Displayname em todos os Tests com a descrição em inglês do que o teste faz.

2022-04-29 19:42 UTC, rafaelluiz-meli commented on src/main/java/com/mercadolivre/bootcamp/projeto_integrador/service/PurchaseOrderItemsServiceImpl.java
> +
Daqui até o final da classe alterar os nomes que contém 'itens' para 'items'

2022-04-29 19:42 UTC, rafaelluiz-meli requested changes
Verifique os comentários e as alterações solicitadas.

2022-04-30 15:44 UTC, alansiq commented
Alterar nome da branch para enhancement, por favor!

2022-05-02 14:45 UTC, rafaelluiz-meli approved these changes

2022-05-02 14:45 UTC, merged